// Auto-generated by Wails v2 in production builds.
// This mock version enables frontend development without Wails CLI.

window.__wailsEventHandlers = window.__wailsEventHandlers || {};

export function EventsOn(eventName, callback) {
  window.__wailsEventHandlers[eventName] = callback;
}

export function EventsOff(eventName) {
  delete window.__wailsEventHandlers[eventName];
}

export function BrowserOpenURL(url) {
  window.open(url, "_blank");
}

export function WindowMinimise() {}
export function WindowMaximise() {}
export function WindowClose() {}
export function Quit() {}
