// Auto-generated by Wails v2 in production builds.
// This mock version enables frontend development without Wails CLI.

const isDev = true; // Wails overrides this file in production

// Mock scan result for UI development
const mockResult = {
  agent_version: "1.0.0",
  scan_id: "mock-scan-001",
  scan_time: new Date().toISOString(),
  scan_duration_ms: 12340,
  host: {
    hostname: "DEV-PC",
    domain: "WORKGROUP",
    os_version: "Windows 11 Pro 23H2",
    arch: "amd64",
    ip_addresses: ["192.168.1.100", "10.0.0.5"]
  },
  summary: {
    total_processes: 187,
    total_connections: 42,
    total_services: 215,
    total_events: 5420,
    detections: { critical: 1, high: 3, medium: 7, low: 12 }
  },
  detections: [
    {
      id: "det-001", type: "lolbin_execution", severity: "critical", confidence: 0.95,
      timestamp: new Date().toISOString(),
      description: "powershell.exe executing encoded command with suspicious parent process",
      process: { pid: 4521, ppid: 1234, name: "powershell.exe", path: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", cmdline: "powershell -enc SQBFAHgA...", parent_name: "cmd.exe", create_time: new Date().toISOString() },
      mitre: { tactics: ["Execution"], techniques: ["T1059.001"] }
    },
    {
      id: "det-002", type: "suspicious_chain", severity: "high", confidence: 0.85,
      timestamp: new Date().toISOString(),
      description: "explorer.exe -> cmd.exe -> powershell.exe chain detected",
      process: { pid: 3201, ppid: 2100, name: "cmd.exe", path: "C:\\Windows\\System32\\cmd.exe", parent_name: "explorer.exe", create_time: new Date().toISOString() },
      mitre: { tactics: ["Execution", "Defense Evasion"], techniques: ["T1059.003"] }
    },
    {
      id: "det-003", type: "suspicious_port", severity: "high", confidence: 0.8,
      timestamp: new Date().toISOString(),
      description: "Connection to suspicious port 4444 (common C2 port)",
      network: { protocol: "TCP", local_addr: "192.168.1.100", local_port: 51234, remote_addr: "45.33.32.156", remote_port: 4444, state: "ESTABLISHED", owning_pid: 5678, process_name: "svchost.exe" }
    },
    {
      id: "det-004", type: "sigma_match", severity: "high", confidence: 0.9,
      timestamp: new Date().toISOString(),
      description: "Sigma: Suspicious PowerShell Download Cradle",
      process: { pid: 4521, ppid: 1234, name: "powershell.exe", path: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", create_time: new Date().toISOString() },
      sigma_rules: ["win_powershell_download"],
      mitre: { tactics: ["Execution"], techniques: ["T1059.001"] }
    },
    {
      id: "det-005", type: "path_anomaly", severity: "medium", confidence: 0.7,
      timestamp: new Date().toISOString(),
      description: "svchost.exe running from non-standard path: C:\\Users\\Public\\svchost.exe",
      process: { pid: 6789, ppid: 1, name: "svchost.exe", path: "C:\\Users\\Public\\svchost.exe", create_time: new Date().toISOString() }
    },
    {
      id: "det-006", type: "typosquatting", severity: "medium", confidence: 0.65,
      timestamp: new Date().toISOString(),
      description: "Possible typosquatting: svch0st.exe (similar to svchost.exe)",
      process: { pid: 7890, ppid: 1, name: "svch0st.exe", path: "C:\\Windows\\Temp\\svch0st.exe", create_time: new Date().toISOString() }
    },
    {
      id: "det-007", type: "service_path_anomaly", severity: "medium", confidence: 0.6,
      timestamp: new Date().toISOString(),
      description: "Service 'UpdateService' running from user temp directory"
    },
    {
      id: "det-008", type: "suspicious_domain", severity: "low", confidence: 0.5,
      timestamp: new Date().toISOString(),
      description: "Connection to suspicious TLD: xyzmalware.tk",
      network: { protocol: "TCP", local_addr: "192.168.1.100", local_port: 52345, remote_addr: "1.2.3.4", remote_port: 443, state: "ESTABLISHED", owning_pid: 3456 }
    }
  ],
  iocs: {
    ips: [
      { value: "45.33.32.156", context: "C2 connection on port 4444" },
      { value: "1.2.3.4", context: "Suspicious TLD connection" }
    ],
    files: [
      { value: "C:\\Users\\Public\\svchost.exe", context: "Path anomaly" },
      { value: "C:\\Windows\\Temp\\svch0st.exe", context: "Typosquatting" }
    ]
  }
};

export async function StartScan() {
  // Simulate scan with progress events
  const steps = [
    { step: 1, stepName: "프로세스 수집 중...", percent: 0, detail: "" },
    { step: 1, stepName: "프로세스 수집 완료", percent: 12, detail: "187개 프로세스" },
    { step: 2, stepName: "네트워크 연결 수집 중...", percent: 12, detail: "" },
    { step: 2, stepName: "네트워크 연결 수집 완료", percent: 25, detail: "42개 연결" },
    { step: 3, stepName: "서비스 수집 중...", percent: 25, detail: "" },
    { step: 3, stepName: "서비스 수집 완료", percent: 37, detail: "215개 서비스" },
    { step: 4, stepName: "레지스트리 스캔 중...", percent: 37, detail: "19개 Persistence 키 검사" },
    { step: 4, stepName: "레지스트리 스캔 완료", percent: 50, detail: "" },
    { step: 5, stepName: "탐지 엔진 실행 중...", percent: 50, detail: "12종 탐지 엔진" },
    { step: 5, stepName: "탐지 엔진 완료", percent: 62, detail: "23건 탐지" },
    { step: 6, stepName: "Sigma 룰 매칭 중...", percent: 62, detail: "" },
    { step: 6, stepName: "Sigma 라이브 매칭 완료", percent: 75, detail: "63룰 적용" },
    { step: 7, stepName: "이벤트 로그 분석 중...", percent: 75, detail: "" },
    { step: 7, stepName: "이벤트 로그 분석 완료", percent: 87, detail: "5420 이벤트 스캔" },
    { step: 8, stepName: "스캔 완료", percent: 100, detail: "총 23건 탐지, 12.3초 소요", done: true },
  ];

  for (const s of steps) {
    await new Promise(r => setTimeout(r, 400 + Math.random() * 600));
    if (window.__wailsEventHandlers?.['scan:progress']) {
      window.__wailsEventHandlers['scan:progress']({ ...s, total: 8, done: s.done || false });
    }
  }

  return mockResult;
}

export async function GetHostInfo() {
  return mockResult.host;
}

export async function IsAdmin() {
  return true;
}

export async function ExportJSON() {
  return "C:\\Users\\User\\Desktop\\ferret_scan_2026-02-07.json";
}

export async function OpenBRIQA() {
  window.open("https://briqa.io", "_blank");
}

export async function GetVersion() {
  return "1.0.0";
}
